# PyTorch Installation and Tensor Basics

### create python virtual environment
python -m venv env_pytorch

### activate
Linux: env_pytorch/bin/activate
Windows: env_pytorch\Scripts\activate

### install pytorch and numpy
pip install numpy
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

In [1]:
import torch

In [3]:
torch.__version__

'2.1.0+cu118'

In [29]:
torch.cuda.is_available()

# if you have GPU and cuda installed
if torch.cuda.is_available():
    device = torch.device("cuda")
    # to create a gpu tensor
    ## with device argument
    x = torch.ones(5, device=device)
    ## to() function
    y = torch.ones(5)
    y = y.to(device)
    # if we do any operation
    z = x + y
    # the computation happens in GPU.

## Tensor Basics

In [6]:
# Create un-initialised tensor
x = torch.empty(1) # more like scalar
x1D = torch.empty(3) # more like 1D array
x2D = torch.empty(2,3) # like 2D array
x3D = torch.empty(2,2,3) # like 3D array....and so on

print(x)
print(x1D)
print(x2D)
print(x3D)

tensor([0.])
tensor([0., 0., 0.])
tensor([[9.4239e-02, 1.5751e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[[9.4727e-02, 1.5751e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [7]:
# Create tensors with some values

## with random values
x = torch.rand(2,2)
print(x)

## with zeros
x = torch.zeros(2,2)
print(x)

## with ones
x = torch.ones(2,2)
print(x)

tensor([[0.1088, 0.1940],
        [0.2970, 0.9193]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [12]:
# Tensor data-types

## look at data types
x = torch.ones(2,2)
print(x.dtype)

## Assign data-types
x = torch.ones(2,2, dtype=torch.int)
print(x,"--",x.dtype)

x = torch.ones(2,2, dtype=torch.double)
print(x,"--",x.dtype)

x = torch.ones(2,2, dtype=torch.float16)
print(x,"--",x.dtype)

# change data-type using "to()"
x = x.to(torch.int64)
print(x,"--",x.dtype)

torch.float32
tensor([[1, 1],
        [1, 1]], dtype=torch.int32) -- torch.int32
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) -- torch.float64
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16) -- torch.float16
tensor([[1, 1],
        [1, 1]]) -- torch.int64


In [13]:
# Tensor sizes
x = torch.ones(2,2)
print(x.size())

# Create a tensor
x = torch.tensor([2.5, 0.1])
print(x, x.size(), x.dtype)

torch.Size([2, 2])
tensor([2.5000, 0.1000]) torch.Size([2]) torch.float32


## Basic Tensor Operations

### Multiple ways of element-wise operations

In [17]:
x = torch.rand(2,2)
y = torch.rand(2,2)

# Element-wise operations

## Add
z1 = x + y
z2 = torch.add(x,y)
print(z1)
print(z2)

### inplace add operation (operation with underscore is an inplace operation in pytorch)
y.add_(x)
print(y)
print("-"*30)

## Sub
z1 = x - y
z2 = torch.sub(x,y)
print(z1)
print(z2)

### inplace add operation (operation with underscore is an inplace operation in pytorch)
x.sub_(y)
print(x)
print("-"*30)

## Mul
z1 = x * y
z2 = torch.mul(x,y)
print(z1)
print(z2)

### inplace add operation (operation with underscore is an inplace operation in pytorch)
y.mul_(x)
print(y)
print("-"*30)

## Div
z1 = x / y
z2 = torch.div(x,y)
print(z1)
print(z2)

### inplace add operation (operation with underscore is an inplace operation in pytorch)
x.div_(y)
print(x)

tensor([[0.3757, 0.9275],
        [0.9583, 1.2475]])
tensor([[0.3757, 0.9275],
        [0.9583, 1.2475]])
tensor([[0.3757, 0.9275],
        [0.9583, 1.2475]])
------------------------------
tensor([[-0.2522, -0.4288],
        [-0.1580, -0.8694]])
tensor([[-0.2522, -0.4288],
        [-0.1580, -0.8694]])
tensor([[-0.2522, -0.4288],
        [-0.1580, -0.8694]])
------------------------------
tensor([[-0.0948, -0.3977],
        [-0.1514, -1.0846]])
tensor([[-0.0948, -0.3977],
        [-0.1514, -1.0846]])
tensor([[-0.0948, -0.3977],
        [-0.1514, -1.0846]])
------------------------------
tensor([[2.6614, 1.0782],
        [1.0435, 0.8016]])
tensor([[2.6614, 1.0782],
        [1.0435, 0.8016]])
tensor([[2.6614, 1.0782],
        [1.0435, 0.8016]])


### Slicing

In [21]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # print first column
print(x[1, :]) # print second row
print(x[1, 1]) # print one value tensor
#if tensor has only one value, .item() can print that scalar value
print(x[1, 1].item()," -- ", type(x[1, 1].item()))

tensor([[0.3840, 0.2553, 0.8853],
        [0.7225, 0.9412, 0.1848],
        [0.7920, 0.8748, 0.5713],
        [0.5624, 0.1805, 0.3166],
        [0.0273, 0.0707, 0.4880]])
tensor([0.3840, 0.7225, 0.7920, 0.5624, 0.0273])
tensor([0.7225, 0.9412, 0.1848])
tensor(0.9412)
0.9412060379981995  --  <class 'float'>


### Reshape

In [23]:
x = torch.rand(4, 4)
print(x)

# .view() reshapes the tensor
## make it 1-D
y = x.view(16)
print(y)

## just mention the last index it automatically calculates the first
y = x.view(-1, 8)
print(y, y.size())

tensor([[0.4978, 0.9954, 0.6430, 0.3816],
        [0.8911, 0.4160, 0.2265, 0.9103],
        [0.8410, 0.1239, 0.9142, 0.1414],
        [0.4923, 0.3160, 0.6626, 0.5412]])
tensor([0.4978, 0.9954, 0.6430, 0.3816, 0.8911, 0.4160, 0.2265, 0.9103, 0.8410,
        0.1239, 0.9142, 0.1414, 0.4923, 0.3160, 0.6626, 0.5412])
tensor([[0.4978, 0.9954, 0.6430, 0.3816, 0.8911, 0.4160, 0.2265, 0.9103],
        [0.8410, 0.1239, 0.9142, 0.1414, 0.4923, 0.3160, 0.6626, 0.5412]]) torch.Size([2, 8])


## Numpy to torch Tensor and vice-versa 

In [24]:
import numpy as np

In [28]:
# Convert torch tensor to numpy
# Numpy can only handle cpu tensors.

a = torch.ones(5)
print(a, type(a))

b = a.numpy()
print(b, type(b))

## .numpy() is not a deep copy, the tensor and the
## corresponding numpy array points to same memory location.
## i.e if we change something in a, same change is reflected in b

a.add_(1)
print(a, type(a))
print(b, type(b))

print("-"*30)

# Convert numpy to torch tensor

a = np.ones(5)
print(a, type(a))

b = torch.from_numpy(a)
print(b, type(b))

## torch.from_numpy() is not a deep copy, the tensor and the
## corresponding numpy array points to same memory location.
## i.e if we change something in a, same change is reflected in b

a += 1
print(a)
print(b)

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.]) <class 'torch.Tensor'>
[2. 2. 2. 2. 2.] <class 'numpy.ndarray'>
------------------------------
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
